name: check_updates

on:
  workflow_dispatch:
  schedule:
    # do this three times a week
    - cron: "0 7 * * 1,3,5"

jobs:
  build:
    name: check updates
    if: github.repository == 'kjanat/dprint-plugin-svgo'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
      - uses: dsherret/rust-toolchain-file@v1
      # setup-node needed for npm install --save in scripts/update.ts
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Run script
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}[bot]"
          deno run -A ./scripts/update.ts

  # This is necessary to prevent GH automatically dsiabling this workflow after 60 days.
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
