name: Release

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: Kind of release
        default: patch
        type: choice
        # major support unknown (@dprint/automation/0.10.3), don't care to check.
        options: [patch, minor]
        required: true

jobs:
  rust:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with: { token: "${{ secrets.DPRINT_PAT }}" }

      - uses: denoland/setup-deno@v2
      - uses: dsherret/rust-toolchain-file@v1

      - name: Bump version and tag
        env:
          GITHUB_TOKEN: ${{ secrets.DPRINT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
          RELEASE_KIND: ${{ github.event.inputs.releaseKind }}
        run: |
          git config user.email "${GH_WORKFLOW_ACTOR}@users.noreply.github.com"
          git config user.name "${GH_WORKFLOW_ACTOR}[bot]"
          deno run -A dprint/automation/publish-release "--${RELEASE_KIND}" Cargo.toml
